### ISSUE TITLE
Need .crt,.key files out of jks.

### ISSUE THREAD

**Issue by Pa1sathvik** [lenchv/jks-js#7]
Hi,

How to create .crt, .key files from jks file using jks-js?

**Comment by lenchv** [comment]
Hi @Pa1sathvik !

Using these instructions:

```
const keyStore = jks.toPem(fs.readFileSync('keystore.jks'), 'password');
```

you'll get the object similiar to this:

```
{
    <alias>: {
         cert: /* content of crt file */,
         key: /* content of key file */,
         ca: /* for truststore there maybe content of certificate authority */
    }
}
```

so to extract pem certificates you have to know password for your jks and alias, where the certs stored. Then you can write them to the file, if you need it.

Please, let me know if it helps

**Comment by Pa1sathvik** [comment]
Thanks @lenchv it worked.
