### ISSUE TITLE
How to get expiry date from jks 

### ISSUE THREAD

**Issue by nirmalrevhari** [lenchv/jks-js#9]
Hi, 
Is there any way to retrieve expiry date/ valid until data here ?
Currently, the parse function returns created date only. 
`[ KeyEntry {
    certType: 'X.509',
    alias: 'nirmal',
    date: 2021-04-21T12:38:05.000Z,
    chain: [ [Certificate] ],`

TIA

**Comment by lenchv** [comment]
Hi @nirmalrevhari !

Well, keystore itself doesn't have expiration, it contains only creation date:
https://github.com/lenchv/jks-js/blob/master/lib/keystore/JavaKeyStoreParser.js#L20

But, you are looking for expiry date of certificate in key entry. So to check the epxiry date, you can take the cert from chain and parse it with some npm module, such as https://www.npmjs.com/package/x509

Please, let me know if it helps, so I can close the issue.

**Comment by nirmalrevhari** [comment]
Hi @lenchv ,

I have tried with cert2json library and it served the purpose. 
Thanks for the lead. Issue resolved now.
